### ISSUE TITLE
support flatpak for wider distro support

### ISSUE THREAD

**Issue by DaRandomCube** [decipher3114/Capter#5]
not every linux user are debian based users, and also not everyone use a mutable distro (there are immutable ones such as steamos)
flatpak supports wider range of distros AND works well with immutable ones
https://flatpak.org/

**Comment by decipher3114** [comment]
Some features of capter doesn't work well with dynamically linked packages on different distro. This is why I have to remove `.tar.gz` from releases, because it is compiled on ubuntu and have issues on archlinux.

It is not issue with capter, but with the crates it uses. Maybe if a better crate is created in future, it will be possible.
