### ISSUE TITLE
[REQUEST] Build support for RPM Package 

### ISSUE THREAD

**Issue by itsnotsos** [decipher3114/Capter#8]
Hey can we get a package for RHEL distros?

**Comment by decipher3114** [comment]
Supporting prebuilts for all three major distros is very uncertain. I have to remove pacman from the prebuilts because of the issue it was having after being built on `ubuntu-latest` on GitHub Actions.

It is very much suggested for you to use `cargo` to install it. It may take time at first to built. But subsequent builds would be faster because of the cache.

It is the suggested method until I find something reliable.
